type: object
properties:
  type:
    type: string
    example: "Passenger"
  destination:
    type: string
    example: "Washington, D.C."
  origin:
    type: string
    example: "New York"
  passengers:
    type: integer
    example: 250
  operator:
    type: string
    example: "michael@gmail.com"