get:
  summary: Get a train by ID
  tags:
    - Trains
  security:
    - userAuth: []
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: Train details
      content:
        application/json:
          schema:
            $ref: '../components/schemas/Train.yaml'
    '401':
      description: 'Forbidden: Insufficient Permission'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Forbidden: Insufficient Permission"
    '403':
      description: 'Forbidden: Insufficient Permission'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Forbidden: Insufficient Permission"
    '404':
      description: Cannot find train with id {id}
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Cannot find train with id {id}"
put:
  summary: Update a train
  tags:
    - Trains
  security:
    - userAuth: []
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: integer
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../components/schemas/TrainRequest.yaml'
  responses:
    '200':
      description: Updated train
      content:
        application/json:
          schema:
            $ref: '../components/schemas/Train.yaml'
    '401':
      description: You are not authenticated
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "You are not authenticated"
    '403':
      description: 'Forbidden: Insufficient Permission'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Forbidden: Insufficient Permission"
    '404':
      description: Cannot find train with id {id}
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Cannot find train with id {id}"
delete:
  summary: Delete a train
  tags:
    - Trains
  security:
    - userAuth: []
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: integer
  responses:
    '204':
      description: No content
    '401':
      description: You are not authenticated
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "You are not authenticated"
    '403':
      description: 'Forbidden: Insufficient Permission'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Forbidden: Insufficient Permission"
    '404':
      description: Cannot find train with id {id}
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Cannot find train with id {id}"